"""Add change paid type

Revision ID: 47a918d77fef
Revises: ca55033b5d51
Create Date: 2025-07-19 15:43:37.311559

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47a918d77fef"
down_revision: Union[str, None] = "ca55033b5d51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "paid",
        existing_type=sa.INTEGER(),
        type_=sa.Double(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "paid",
        existing_type=sa.Double(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
