"""Add relationships

Revision ID: 984c6d05cc9c
Revises: 98e1f5b80d80
Create Date: 2025-07-15 20:29:37.250482

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "984c6d05cc9c"
down_revision: Union[str, None] = "98e1f5b80d80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "items", ["id"])
    op.drop_constraint(op.f("items_order_id_fkey"), "items", type_="foreignkey")
    op.create_foreign_key(
        None, "items", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "orders", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_constraint(None, "items", type_="foreignkey")
    op.create_foreign_key(
        op.f("items_order_id_fkey"), "items", "orders", ["order_id"], ["id"]
    )
    op.drop_constraint(None, "items", type_="unique")
    # ### end Alembic commands ###
