"""Add orders table

Revision ID: 98e1f5b80d80
Revises:
Create Date: 2025-07-15 17:31:12.306660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98e1f5b80d80"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("initiator", sa.String(), nullable=True),
        sa.Column("by_order", sa.String(), nullable=True),
        sa.Column("by_bank", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("price_by_one", sa.Double(), nullable=False),
        sa.Column("check", sa.Boolean(), nullable=True),
        sa.Column("return_count", sa.Integer(), nullable=True),
        sa.Column("return_check", sa.Boolean(), nullable=True),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    op.drop_table("orders")
    # ### end Alembic commands ###
