"""Change to null

Revision ID: ca17860e0e51
Revises: e78106967622
Create Date: 2025-07-18 10:42:01.488803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca17860e0e51"
down_revision: Union[str, None] = "e78106967622"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "items",
        "price_by_one",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("orders", "date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "items",
        "price_by_one",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("items", "count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
