"""Add created date field

Revision ID: ca55033b5d51
Revises: 53f954c371eb
Create Date: 2025-07-19 15:17:29.903343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca55033b5d51"
down_revision: Union[str, None] = "53f954c371eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("created_dt", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("created_dt", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "created_dt")
    op.drop_column("items", "created_dt")
    # ### end Alembic commands ###
